-- This file allow to write SQL commands that will be emitted in test and dev.
-- The commands are commented as their support depends of the database
-- insert into myentity (id, land) values(1, 'land-1');
-- insert into myentity (id, land) values(2, 'land-2');
-- insert into myentity (id, land) values(3, 'land-3');
-- alter sequence myentity_seq restart with 4;