CREATE SCHEMA if not exists db;

-- Create Authentication Table
CREATE TABLE db.authentication
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255),
    password VARCHAR(255)
);

-- Create Company Table
CREATE TABLE db.company
(
    companyID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255),
    VAT       BIGINT,
    pin       INT
);

-- Create Collaborator Table
CREATE TABLE db.collaborator
(
    collaboratorID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255),
    companyID      INT,
    role           VARCHAR(255),
    FOREIGN KEY (companyID) REFERENCES company (companyID)
);

-- Create Land Table
CREATE TABLE db.land
(
    landID       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255),
    area         INT,
    coordinates  VARCHAR(255),
    localization VARCHAR(255),
    companyID    INT,
    FOREIGN KEY (companyID) REFERENCES company (companyID)
);

-- Create Culture Table
CREATE TABLE db.culture
(
    cultureID   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    date        TIMESTAMP,
    description TEXT,
    landID      INT,
    FOREIGN KEY (landID) REFERENCES land (landID)
);

-- Create Status History Table
CREATE TABLE db.status_history
(
    statusHistoryID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date            TIMESTAMP,
    description     TEXT,
    image           BYTEA,
    cultureID       INT,
    FOREIGN KEY (cultureID) REFERENCES culture (cultureID)
);

-- Create Product Table
CREATE TABLE db.product
(
    productID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255)
);

-- Create Treatment Table
CREATE TABLE db.treatment
(
    treatmentID  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    productID    INT,
    cultureID    INT,
    description  TEXT,
    date         TIMESTAMP,
    securityDays INT,
    FOREIGN KEY (productID) REFERENCES product (productID),
    FOREIGN KEY (cultureID) REFERENCES culture (cultureID)
);

CREATE SEQUENCE db.authorization_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE db.collaborator_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE db.company_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE db.land_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE db.culture_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE db.status_history_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE db.product_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE db.treatment_seq START WITH 1 INCREMENT BY 1;
